name: Build Rust SDK

on:
  workflow_dispatch:
  pull_request:

jobs:
    test_build_rust:
        name: Build Rust SDK
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest
        strategy:
            matrix:
                target: ["nanox", "nanosplus", "stax", "flex"]
        steps:
            - name: Clone C SDK
              uses: actions/checkout@v4
              with:
                path: c_sdk
                ref: master
            - name: Clone
              uses: actions/checkout@v4
              with:
                  repository: LedgerHQ/ledger-device-rust-sdk
                  ref: master
                  path: rust_sdk
            - name: Cargo build
              working-directory: rust_sdk/ledger_device_sdk
              run: |
                  cargo +$RUST_NIGHTLY build --target ${{ matrix.target }} --config=env.LEDGER_SDK_PATH="../../c_sdk"
