name: Build all Rust apps

on:
  pull_request:

jobs:
    test_build_rust:
        name: Build all Rust apps
        uses: LedgerHQ/ledger-device-rust-sdk/.github/workflows/reusable_build_all_apps.yml@y333/update_ci
        with:
            c_sdk_branch: ${{ github.head_ref }}